name: Deploy

on:
  push:
    tags: [ 'v*' ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Generate resourcepacks
        run: $GITHUB_WORKSPACE/scripts/generate_resourcepacks.sh

      - name: Generate signatures
        run: |
          sha1sum $GITHUB_WORKSPACE/target/resourcepack_v3.zip | cut -b -32 \
          > $GITHUB_WORKSPACE/target/resourcepack_v3.zip.sha1
          sha1sum $GITHUB_WORKSPACE/target/resourcepack_v4.zip | cut -b -32 \
          > $GITHUB_WORKSPACE/target/resourcepack_v4.zip.sha1

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}

      - name: Upload v3 resourcepack
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./target/resourcepack_v3.zip
          asset_name: resourcepack_v3.zip
          asset_content_type: application/zip

      - name: Upload v4 resourcepack
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./target/resourcepack_v4.zip
          asset_name: resourcepack_v4.zip
          asset_content_type: application/zip

      - name: Upload v3 signature
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./target/resourcepack_v3.zip
          asset_name: resourcepack_v3.zip.sha1
          asset_content_type: text/plain

      - name: Upload v4 signature
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./target/resourcepack_v4.zip
          asset_name: resourcepack_v4.zip.sha1
          asset_content_type: text/plain
